### ISSUE TITLE
The colors are not rendering 

### ISSUE THREAD

**Issue by Devyani20** [lentschi/ngx-nested-ellipsis#2] opened 2021-03-04 10:29 UTC
If a color is given to a span or a paragraph its is not coming there

For example :
if a give this text :<span style='color:#fa6400'>I am red</span>
the output should be : 
![image](https://user-images.githubusercontent.com/57898970/109950330-67cfa480-7d02-11eb-977c-4510496f53e3.png)

but the output we get is :
![image](https://user-images.githubusercontent.com/57898970/109950467-8b92ea80-7d02-11eb-8f40-3161c32ca139.png)

**Comment by lentschi** [comment] 2021-03-05 09:49
Could you please provide the markup/code to reproduce this issue (preferably via StackBlitz)

Here's a StackBlitz color sample, where colors work fine - maybe just fork this to provide a failing sample:
https://stackblitz.com/edit/ngx-nested-ellipsis-colors-sample?file=src%2Fapp%2Fapp.component.html

**Comment by Devyani20** [comment] 2021-03-05 10:16
This issue comes when you pass text via innerHTML

**Comment by Devyani20** [comment] 2021-03-05 10:19
And i more thing when i was adding only image tag via innerHTML the show more link does not come up
![MicrosoftTeams-image (11)](https://user-images.githubusercontent.com/57898970/110102041-4b973a80-7dca-11eb-87b9-e9ae2873a268.png)

**Comment by lentschi** [comment] 2021-03-05 10:26
You probably just forgot to use [bypassSecurityTrustHtml](https://stackoverflow.com/questions/31548311/angular-html-binding#answer-41089093).

See this StackBlitz sample:
https://stackblitz.com/edit/ngx-nested-ellipsis-bypass-security-trust-html?file=src/app/app.component.ts

**Comment by Devyani20** [comment] 2021-03-05 10:28
ok Thanks @lentschi

**Comment by lentschi** [comment] 2021-03-05 10:32
You're welcome. :blush: I just added your image too: https://stackblitz.com/edit/ngx-nested-ellipsis-bypass-security-trust-html?file=src%2Fapp%2Fapp.component.css

Please tell me, if it works for you too, so I can close this ticket.

**Comment by Devyani20** [comment] 2021-03-08 08:50
still not able to use it  
https://stackblitz.com/edit/github-m7ud36?file=src/app/app.component.ts

**Comment by lentschi** [comment] 2021-03-08 10:44
You're right: `ngx-nested-ellipsis` doesn't detect content size changes (such as when an image has been loaded); only changes of the element's border-box.

So a simple workaround is to provide image dimensions:
https://stackblitz.com/edit/ngx-nested-ellipsis-image-sample1?file=src%2Fapp%2Fapp.component.ts
(Providing image dimension is something you should do whenever possible - event without ngx-nested-ellipsis as it improves rendering performance.)

I'm closing this ticket now (The colors issue seems to be resolved), but I've created a bug ticket here: https://github.com/lentschi/ngx-nested-ellipsis/issues/3

**Closed by lentschi** 2021-03-08 10:44 UTC

**Comment by lentschi** [comment] 2021-03-08 11:01
@Devyani20 I just fixed it - see https://github.com/lentschi/ngx-nested-ellipsis/issues/3#issuecomment-792674834

Thanks for reporting this!

**Comment by Devyani20** [comment] 2021-03-08 11:07
Thank you  It's working now
